// <auto-generated />
namespace LamVinhLoc_2011064018_THWEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TaobangCoursesvaCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaobangCoursesvaCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202303080332218_Tao bang Courses va Categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
